# Generated by Django 5.1.7 on 2025-03-15 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_news_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name": "Новости", "verbose_name_plural": "Новости"},
        ),
    ]
